### ISSUE TITLE
Support "Visual Studio for Mac"

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism-Extensibility#1]
Ok so the name is deceptive it's really just the next major version of Xamarin Studio with a new skin. But either way it would be good to have parallel support for Xamarin Studio 6.X and Xamarin Studio 7.X (rebranded as Visual Studio for Mac).

Pretty sure this would require having a duplicate of the `addin-project.xml` with `appVersion="7.0"` and then setup a build to look at the duplicate. This should allow parallel support for both versions so new features can continue to be added.

**Comment by rupreetg** [comment]
Do we have any timelines for supporting Visual Studio for Mac? Given VS for Mac is the only IDE available for Xamarin, prism support is needed.

**Comment by dansiegel** [comment]
I have some updates for the VS4Mac templates, but there seems to be an issue with the mono addin site not building it. Unfortunately I haven't had the time to determine why.

**Comment by newky2k** [comment]
Hi Dan,

You could create a mpack file and provide a link from github, then they could use the "Install from file" option.  This site show the details http://www.monodevelop.com/developers/articles/publishing-an-addin/,  though you'll need to use "vstool" now if you only have VS4Mac.

**Comment by cassionandi** [comment]
Someone have this mpack ready to install?

**Comment by dansiegel** [comment]
Unfortunately the Mono Addins site is being deprecated, and they haven't been very responsive in fixing the addins server.
this may be changed later: You can now install the Templates on VS4Mac. Go to `Visual Studio` => `Extensions`, select the `Gallery` tab, click the `Repository` drop down, and select `Manage Repositories...`
Add `https://prism.azureedge.net/main.mrep`

**Comment by ruaan** [comment]
@brianlagunas Let's add this to the readme on master ?
