### ISSUE TITLE
Flatten project folder structure + wish list

### ISSUE THREAD

**Issue by developer9969** [PrismLibrary/Prism-Extensibility#10]
Hi
When creating a new solution using the prism template or xamarin ones currently it creates projects within 2 sets of folders
Would it be possible to flatten the folder structure instead of having a folder within a folder.
like
SolutionName
   MyApp.proj (folder)  
   MyApp.droid (folder)
   MyApp.iOS (folder)

Change Targetprofile to be aligned with xamarin. 

Templates 
Is it possible to add  a Prism Xamarin Module template
An Android class library and ios Template 
Sometimes you just want to add a project not the all thing.

Just a wish list 
Many thanks!!!

**Comment by dansiegel** [comment]
I'm not sure I follow your issue with the template structure. Each project is in the root of the directory where you create the solution. Can you provide a little clarification on what you see vs what you want to see.

**Comment by developer9969** [comment]
Sorry for not being clear  regarding the flattening of the folder structure. 
Let suppose I want to create a new solution  "PrismMasterDetailSample" solution

1. Create a solution using the Prism.XamarinForms template.
2.It now creates this structure
![image](https://user-images.githubusercontent.com/16970109/28750693-fc918bc6-74e9-11e7-9d08-4a9f740f5a1f.png)

As you can see it has created a root folder called PrismMasterDetailSample and you click on that and you get 
![image](https://user-images.githubusercontent.com/16970109/28750703-4cb4baf6-74ea-11e7-9ee9-3e464aa8ce82.png)

Wanted result when you create a solution is below
![image](https://user-images.githubusercontent.com/16970109/28750716-d1e9ae48-74ea-11e7-8856-95ec5833760d.png)

Removing 1 useless folder directory will also avoid the problem with the length of the path issue
What we tend to do is quite messy ,as we have to unload each project file and remove the extra "..\"

Hope makes sense

**Comment by opcodewriter** [comment]
+1.
Also, this would align to the folder structure generated by the Xamarin Forms project template.

**Comment by brianlagunas** [comment]
Since we no longer support Xamarin Studio, this issue will be closed. We have a plugin or VS for Mac now :)
