### ISSUE TITLE
Xamarin Forms - UWP platform specific project is missing from the solution

### ISSUE THREAD

**Issue by stepanic** [PrismLibrary/Prism-Extensibility#11]
When I try to choose UWP as platform, then platform specific project in Xamarin.Forms solution in not created, also I tried to create solution only with UWP and with all three platforms iOS, Android and UWP, UWP platform specific project is always missing.

I am using Visual Studio 2015 Community but I do not have installed UWP tools, could you please disable check of UWP platform if UWP tools are not installed if this is a reason because platform specific project is not created.

![step1](https://user-images.githubusercontent.com/315282/29601644-d6f0a2ca-87dc-11e7-91ab-604f8dc12339.PNG)
![step2](https://user-images.githubusercontent.com/315282/29601645-d6f8895e-87dc-11e7-83c2-1acf24e22915.PNG)
![step3](https://user-images.githubusercontent.com/315282/29601646-d6f9ca30-87dc-11e7-876b-9503189d7686.PNG)

**Comment by brianlagunas** [comment]
>  but I do not have installed UWP tools

This is why it is not being created.  You can't create a UWP app if you don't have UWP installed.

The simple fix, just don't check UWP.
