### ISSUE TITLE
Error when trying to create new Prism Blank App (WPF)

### ISSUE THREAD

**Issue by jaras** [PrismLibrary/Prism-Extensibility#18]
When trying to create a new Prism Blank App (WPF) I get the error in the picture and I end up with an empty solution.

I found a reference to the error here but the fix is to change the decimal separator from comma (,) to a dot (.).

If the fix is used while creating the project and I change the region setting back I can still open the project afterwards.

This is on vs2017 using the danish region format in the Windows Region Settings.

![image](https://user-images.githubusercontent.com/123031/32698733-90bd5fce-c7aa-11e7-959b-7e5271514f08.png)

Link to the page describing the "solution"
https://digitalsupport.ge.com/communities/en_US/Article/Error-Microsoft-Build-Utilities-ToolLocationHelper-GetPathToStandardLibraries

**Comment by brianlagunas** [comment]
This seems to be related to non-English versions of Visual Studio.  When you create the project, can you open the generated app's csproj file in NOtePad and let me know what the TargetFrameworkVersion elements value is?

Also, can you navigate to `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ProjectTemplates\CSharp\Windows Root\Windows\1033\WPFApplication` and open the WPFApplication.csproj file and copy it's contents into this issue?

**Comment by jaras** [comment]
When it is not working the TargetFrameworkVersion is 47 but if I change it to 4.7 and add the project to a solution it works.

It does not happen when I create a VisualStudio WPF project.

[WPFApplication.txt](https://github.com/PrismLibrary/Prism-Extensibility/files/1464894/WPFApplication.txt)

**Comment by brianlagunas** [comment]
A fix has just been uploaded to the marketplace.  Please update and let me know if you are still having issues.
