### ISSUE TITLE
Bugs that delete files in the solution

### ISSUE THREAD

**Issue by juniair** [PrismLibrary/Prism-Extensibility#19]
Hi 
I was building a project module. I chose the new project from the solution and chose the prism module project. I accidentally closed the popup window that appeared afterwards. At that moment all the folders and files in the solution were deleted. Is this a bug?

The environment I worked on is as follows.
  - Windows 10 professional 64bit
  - Visual Studio 2017 community

**Comment by brianlagunas** [comment]
It could be a bug.  The module should have been the only thing that was deleted, not everything.  Let me look into this.

Thanks for reporting

**Comment by brianlagunas** [comment]
Yes, this is a bug. Great find!  I will get this fixed and let you know when the update is availabe

**Comment by brianlagunas** [comment]
Update to 2.0.6 and try again. Let me know if you have any other issues.
