### ISSUE TITLE
Remove `Views` & `ViewModels` from namespaces in XS Templates

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism-Extensibility#2]
Xamarin Studio provides support for both Flat and Hierarchal namespacing. The templates are currently setup for people with Flat namespacing set. This produces Prism Templates with namespaces like `MyApp.Views.Views.MainPage` & `MyApp.ViewModels.ViewModels.MainPageViewModel`. 

Since Flat namespacing is just bad practice, we should default to supporting environments with Hierarchal namespacing set, unless/until we can determine a way dynamically set this depending on environmental settings.

**Comment by hminaya** [comment]
@dansiegel why is MyApp.Views.Views.MainPage bad? Prism relies on this (and other) conventions to work seamlessly without having to specify everything in the bootstrapper.

**Comment by dansiegel** [comment]
@hminaya there are a couple of issues here
1) Xamarin Studio defaults to a Flat namespacing convention which is why the item templates had `{namespace}.Views` and `{namespace}.ViewModels`. That said, it's a bad practice and developers should be using Hierarchal namespacing.
2) If you are generating files as I mentioned above the ViewModelLocator will not be able to locate your ViewModel because it is in the wrong namespace. It would be looking for `MyApp.Views.ViewModels.MainPageViewModel` not `MyApp.ViewModels.ViewModels.MainPageViewModel`

**Comment by brianlagunas** [comment]
I think going forward I will only target VS for Mac instead of XS.  This will probably still need to be addressed though.
