### ISSUE TITLE
can't get ef core to work

### ISSUE THREAD

**Issue by topfunet** [PrismLibrary/Prism-Extensibility#20]
I can't get ef core to work.
If i add Entity Framework Core 2.0 to the shared project then run the android project, program will immediately close.
IOS and UWP works perfectly fine,just android.

**Comment by dansiegel** [comment]
@topfunet If you create an Android app, does EF work? There is nothing about Prism or the templates that should have anything to do with EF

**Comment by brianlagunas** [comment]
You will need to provide more information as this is most likely not related to Prism.  Do you get an exception, or any type of error message?

**Comment by brianlagunas** [comment]
Do you have a sample that you can provide that we debug?

**Comment by topfunet** [comment]
This CAN work:
1. create a xamarin.forms project.
2. delete pcl project, create .net standard 2.0 project and install xamarin.forms.dll, then copy old pcl's files to new standard project.
3. install ef core 2.0 to shared project and android project.
4. run android app, everything's ok.

This CAN NOT work:
1. create a PRISM xamarin.forms project.
2. because shared project is .net standard 2.0 project, so no need to replace it.
3. install ef core 2.0 to shared project.
4. run android app, with no error message, just with white screen then close program and vs2017.

**Comment by brianlagunas** [comment]
Can you please provide a running sample.  Also, can you provide the csproj file of the Andrdoi project that works

**Comment by brianlagunas** [comment]
Keep in mind that the only different between the two android projects is that the Prism Template Pack uses the PackageReference to add NuGets instead of a packages.config or project.json.  That's why it is important you provide a complete sample, as it is difficult to determine the root cause of your issue.

**Comment by topfunet** [comment]
[samples.zip](https://github.com/PrismLibrary/Prism-Extensibility/files/1468052/samples.zip)

**Comment by topfunet** [comment]
Actually, you can create a solution, and add shared project and android project, run android project should see the result.

**Comment by brianlagunas** [comment]
Are you saying that the Android project in general isn't working regardless of having EF?

**Comment by topfunet** [comment]
no, android project is working, but if i add Microsoft.EntityFrameworkCore.Sqlite to shared project, android project isn't working.

**Comment by brianlagunas** [comment]
I can duplicate the issue.  This is very strange as the project files are near identical.  The only difference is how the NuGet packages are added.  I'll keep playing around, but this may be a bug in VS.

**Comment by topfunet** [comment]
I am really hoping this can be fixed, because now ef is a very important part in dotnet world.

**Comment by brianlagunas** [comment]
Not in Xamarin.Forms. You should be using a service API in an XF app.  I will have to send this off to Microsoft as I believe this is an issue with Visual Studio and netstandard.  Direct DB connections from a mobile app are not a good practice.

**Comment by brianlagunas** [comment]
So this is definitely an issue with Visual Studio. I removed everything prism from the project and made it a pure XF project, and the issue still persists.  I will report this issue to MS and see what they say.

**Comment by topfunet** [comment]
OK, thank you for your patience, and keep me posted.

**Comment by brianlagunas** [comment]
In the meantime, just convert it to a packages.config project.

Edit the Android.csproj and remove
```
    <CopyNuGetImplementations>true</CopyNuGetImplementations>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
```
Then right click the solution and install the `Prism.DryIoc.Forms` Nuget package into the Android project.  That should get you running again.

**Comment by topfunet** [comment]
It's still not working.
If I remove CopyNuGetImplementations and RestoreProjectStyle, then install Microsoft.EntityFrameworkCore.Sqlite, and still not working.

**Comment by topfunet** [comment]
Finally it's working.
Remove CopyNuGetImplementations and RestoreProjectStyle, install Prism.DryIoc.Forms is working.

**Comment by topfunet** [comment]
I saw the template change back, but still not working.
Maybe just convert shared project to standard, not app project, because i just found if i install Xamarin.Forms.dll to Android project will not install Xamarin.Android.** dependency.

**Comment by brianlagunas** [comment]
The platform projects are not .NET Standard projects.  They are normal projects.  The only difference is how the NuGets are added via the PackageRefernce.  I am now using the exact same templates shipping in the VS2017 15.5 preview.  I tested this against the latest VS2017 15.5 preview template sthat MS ships and the issue exists there.  So this is not a problem with Prism.  This is an issue with the actual VS templates, the build system, or possible EF itself.

**Comment by topfunet** [comment]
I got it.
Hope MS will fix in the next version, In the mean time I will manually add Prism.DryIoc.Forms to my projects.
And Prism is a great package, really love it.

**Comment by brianlagunas** [comment]
Me too.

**Comment by brianlagunas** [comment]
FYI, it seems there has been a workaround posted on the EF GitHub site.  Seems many people are running into this:

https://github.com/aspnet/EntityFrameworkCore/issues/8922

**Comment by topfunet** [comment]
I just tested this, it's working.
Thank you very much!!!

**Comment by topfunet** [comment]
I just found not just ef core, lots of packages all have similar bug, like Automapper.
Seems like packages.config is the only way get xamarin to work.
