### ISSUE TITLE
Prism template pack - VS 2015

### ISSUE THREAD

**Issue by paulb2099** [PrismLibrary/Prism-Extensibility#22]
Hi,

I can not get the Prism Template pack to install for VS 2015 Enterprise.
I get the following error:
![image](https://user-images.githubusercontent.com/5104961/32775383-65031a42-c983-11e7-861f-535f47532dc4.png)

I remember successfully installing the template pack for VS 2015 Community a few months back.
I'm wondering if the Prism Template pack now only supports VS 2017. I hope this isn't the case.

**Comment by bartlannoeye** [comment]
Hey @paulb2099 , if you want to use Prism Template Pack for VS 2015 Enterprise, you will have to use version 1.x.

Prism Template Pack v2 only supports Visual Studio 2017 because of .NET Standard. More info in [Brian's blog post](http://brianlagunas.com/prism-template-pack-2-0/).

**Comment by paulb2099** [comment]
Hi,

Thanks for such a quick reply.

Any ideas on where I can get the Prism Template Pack v1.x.
I can only seem to find the latest version online.

**Comment by bartlannoeye** [comment]
Didn't know that the VS Marketplace didn't work like NuGet when it comes to versioning.

@brianlagunas ?

**Comment by brianlagunas** [comment]
The market place does not allow you to get older versions.  The current version only supports VS2017 as the templates are using the new dotnet templating system and generate netstandard projects which are not supported in VS2015
