### ISSUE TITLE
Snippets not working

### ISSUE THREAD

**Issue by TianVan** [PrismLibrary/Prism-Extensibility#26]
after update prism-template plugin，snippets not working

**Comment by brianlagunas** [comment]
Try uninstalling and reinstalling.  VS has issues sometimes with automatic updates.  This has already been reported to Microsoft.

**Comment by TianVan** [comment]
I've tried twice. the problem is still there.

**Comment by brianlagunas** [comment]
When you uninstall, go toy our snippet manager and see if the Prism snippets are under the CSharp language.  If, so they will more than likely have a warning icon on the Prism folder.  Delete it, and then reinstall the template pack.  The open your code snippet manager again and you should see the Prism snippets. If you still have the warning icon, then you can manually fix it.

![image](https://user-images.githubusercontent.com/835562/34909378-e4cb8f9a-f85c-11e7-8d0c-ee76290ea3aa.png)
