### ISSUE TITLE
Visual studio for mac support

### ISSUE THREAD

**Issue by ccallaghan** [PrismLibrary/Prism-Extensibility#28]
I watched this video (https://www.youtube.com/watch?v=CCbwnIJGZp8) in which you ask someone to contribute and fix the visual studio for mac prism Xamarin forms extension.
I submitted a PR that does that, but you just removed the code from the repo. 
Are you planning on rewriting a new extension?

**Comment by dansiegel** [comment]
As I mentioned the addin is being updated to use the same dotnet Templates that the VS2017 extension uses. Your PR was closed because it does not achieve what we’re looking for in the next update.

**Comment by ccallaghan** [comment]
Sure that's good news, let me know if there is anything I can do to help.

**Comment by brianlagunas** [comment]
Done! The Prism Template Pack for Mac is now available in the gallery.
