### ISSUE TITLE
Could Not Create The Project

### ISSUE THREAD

**Issue by ronakshethia** [PrismLibrary/Prism-Extensibility#31]
i am getting project cannot created error
with the following error 
![image](https://user-images.githubusercontent.com/35444818/35805118-9f03db88-0aa0-11e8-81dc-34adde43d617.png)

![image](https://user-images.githubusercontent.com/35444818/35805151-c16a754c-0aa0-11e8-9154-735e6ee70ded.png)

**Comment by brianlagunas** [comment]
This most likely means you don't have the Net Core packages installed in VS, which is required.  Modify your VS installation and install the NET Core development packages.

**Comment by ronakshethia** [comment]
Hi Sir,
I identified the issue and issue was my xamarin was not updated and so i
updated my xamarin to 4.8 and my problem got solved,
Thank You,

Regards,
Ronak
