### ISSUE TITLE
Issue Creating Project on Visual Studio for Mac

### ISSUE THREAD

**Issue by richard3357** [PrismLibrary/Prism-Extensibility#35]
I am pretty sure that this is specific to just the Prism app template but when trying to create an app from a Prism on Mac I just get a dialog saying the Project couldn't be created. This is when trying to create a Blank App or a Quick Start app. 

I tried to read the log (which I uploaded) but it didn't seem prism related, however it only happens when I try and create an app from a Prism Template, trying to create any other project works fine. The best error to look at is the last one (ignore the error for missing permissions, tried to put the project at the root of the hard drive to see if the length of the file path was too much). 

[Ide.2018-02-15__18-23-24.log](https://github.com/PrismLibrary/Prism-Extensibility/files/1728926/Ide.2018-02-15__18-23-24.log)

**Comment by richard3357** [comment]
Uninstalling the Prism Quickstart Templates fixed this issue, might be something to do with the fact Prism Templates is version 2.0.0 and Prism Quickstart Templates is version 1.4.0?

**Comment by dansiegel** [comment]
The two template packs have problems running side by side... they both run fine as long as the other one isn't present. It's an issue that I'm aware of... they target very different audiences. The Prism Templates offer a flat no frills experience essentially what you get from Visual Studio when creating a Xamarin Forms Application except using Prism... The QuickStart has more features than I can list here...
