### ISSUE TITLE
Issue creating a Prims project

### ISSUE THREAD

**Issue by simon25608** [PrismLibrary/Prism-Extensibility#36]
Hello,

I get the following error when creating a blank project of prism

![2018-02-20_084432](https://user-images.githubusercontent.com/18722357/36412455-ace4825e-161a-11e8-96fd-973bfcb0366e.jpg)

 I no longer reach the wizzard to choose the container

Version plugin: 2.0.8
Version vs: Comunity 15.5.6

Thanks

**Comment by dansiegel** [comment]
@simon25608 Ninject is no longer a supported container for Prism 7 with Xamarin Forms. Thanks for letting us know about the issue though :)

**Comment by simon25608** [comment]
okay! Thanks for responding. Would a correction for this problem be possible? Because I can not use your fantastic template.

**Comment by brianlagunas** [comment]
Yes, launch regedit and delete the following key HKEY_CURRENT_USER\Software\Prism\SelectedContainer
