### ISSUE TITLE
The specified key was not present in the dictionary

### ISSUE THREAD

**Issue by ruattolo** [PrismLibrary/Prism-Extensibility#37]
Hello

i have update vs2017 to version 15.6.0 and wizard for cration a Prism module (Xamarin.forms) give me a error :

"the specified key was not present in the dictionary"

Can you help me?? thank's

**Comment by TheAifam5** [comment]
I have also that problem when I creating Blank WPF application with Unity, Autofac and Dryloc.
So the extension is dead for this VS2017 15.6.0 update.

**Comment by trevor-turner** [comment]
I also have the same issue. I am unable to create a bank WPF VS2017 15.6.1. A college has the same issue he is using 15.6.0

**Comment by ChrisReddy** [comment]
I am also experiencing the same issue. I tried a Prism Blank App (WPF) and a Prism Module(WPF). I also tried selecting any of the 3 different Dependency injection types all with the same results. I am using VS2017 15.6.1

**Comment by brianlagunas** [comment]
Thanks for reporting this. Sounds like VS2017 15.6 has broken something. Now I'm scared to upgrade to test it out :)

**Comment by brianlagunas** [comment]
Just curious before I update my VS version. Has anyone tried uninstalling and reinstalling the Prism Template Pack to see if that fixes it? I'm wondering if the VS update it trashing the extensions folders.

**Comment by trevor-turner** [comment]
I have tried removing the template and re-adding it on VS2017 15.6.1. Still having the same issue. I have installed on 15.5.7 on a VS2017 that did not have the template. It worked as expected. So the problem is with 15.6.x

**Comment by brianlagunas** [comment]
Thanks @trevor-turner. I guess Microsoft did break something. We will see if we can find out what they broke.

**Comment by trevor-turner** [comment]
Please vote for bug-fix on Developer Community User Voice
https://developercommunity.visualstudio.com/content/problem/212477/unable-to-create-a-prism-project-from-the-template.html

**Comment by TheAifam5** [comment]
Its must be problem with the extension, not with Visual Studio, because I was able to create the WPF Prism project once, and after I removed the project - does not work anymore. I downloaded today an VS update.

**Comment by brianlagunas** [comment]
The extension has not changed. Whereas Visual Studio has released a number of updates. Now the extension doesn't work. it works fine in 15.5.7 and earlier. So VS changed something. We will have to try and find out what that is.

**Comment by TheAifam5** [comment]
That was pretty easy to find.
So, actually when we gonna create a project, we going directly to select the Prism project, but there is no selection box for the Framework version which we want to use and therefore throws an exception on the line 33 in file SelectContainerWizard.cs.

But... When we the first, select the .NET project and we will change the .NET framework version (that i tested already, maybe is only needed to go there and go back to the Prism project selection) and then we are able to create a new project because the contains now "$targetframeworkversion$".

That all what I found.

**Comment by brianlagunas** [comment]
I just finished upgrading my VS207 to the latest, and I see what you are talking about.  I can't believe VS would just remove that option like that. I'm going to yell at the extensibility team now!

**Comment by TheAifam5** [comment]
It’s only small change :) I actually like that change because I can now make a project and define specific framework version :) That can be added as feature :D

**Comment by brianlagunas** [comment]
Fixed! I'll try to get an update out by tomorrow

**Comment by brianlagunas** [comment]
I have pushed an update. Please test it an make sure it works :)
