### ISSUE TITLE
error "cannot save '.\..\projects\WpfApp1\PrismModule1\Module.cs' as it is not open in the editor

### ISSUE THREAD

**Issue by mamataveeranna** [PrismLibrary/Prism-Extensibility#6]
Error related to prism template in vs2017 community edition. Added prism template extension template. Created the unity app. While adding module to the added prismapp. VS throws error "cannot save '.\..\projects\WpfApp1\PrismModule1\Module.cs' as it is not open in the editor.

**Comment by brianlagunas** [comment]
this has been fixed.  You'll see it in the next update.  Thanks for reporting it
